# Autogenerated by `bun2nix`, editing manually is not recommended
#
# Set of Bun packages to install
#
# Consume this with `fetchBunDeps` (recommended)
# or `pkgs.callPackage` if you wish to handle
# it manually.
{
  copyPathToStore,
  fetchFromGitHub,
  fetchgit,
  fetchurl,
  ...
}:
{
  "@danoaky/js-utils@0.29.2" = fetchurl {
    url = "https://registry.npmjs.org/@danoaky/js-utils/-/js-utils-0.29.2.tgz";
    hash = "sha512-n4BEibCLEl+gaXDHxHcZjNndWgvKkqB4iX4enAgFxEnBJnF9L4gE7VBJQpFBkN3zwBSgCGVpnkHsWA7JE3gPBA==";
  };
  "@sec-ant/readable-stream@0.4.1" = fetchurl {
    url = "https://registry.npmjs.org/@sec-ant/readable-stream/-/readable-stream-0.4.1.tgz";
    hash = "sha512-831qok9r2t8AlxLko40y2ebgSDhenenCatLVeW/uBtnHPyhHOvG0C7TvfgecV+wHzIm5KUICgzmVpWS+IMEAeg==";
  };
  "@sindresorhus/merge-streams@4.0.0" = fetchurl {
    url = "https://registry.npmjs.org/@sindresorhus/merge-streams/-/merge-streams-4.0.0.tgz";
    hash = "sha512-tlqY9xq5ukxTUZBmoOp+m61cqwQD5pHJtFY3Mn8CA8ps6yghLH/Hw8UPdqg4OLmFW3IFlcXnQNmo/dh8HzXYIQ==";
  };
  "@types/braces@3.0.5" = fetchurl {
    url = "https://registry.npmjs.org/@types/braces/-/braces-3.0.5.tgz";
    hash = "sha512-SQFof9H+LXeWNz8wDe7oN5zu7ket0qwMu5vZubW4GCJ8Kkeh6nBWUz87+KTz/G3Kqsrp0j/W253XJb3KMEeg3w==";
  };
  "@types/bun@1.3.9" = fetchurl {
    url = "https://registry.npmjs.org/@types/bun/-/bun-1.3.9.tgz";
    hash = "sha512-KQ571yULOdWJiMH+RIWIOZ7B2RXQGpL1YQrBtLIV3FqDcCu6FsbFUBwhdKUlCKUpS3PJDsHlJ1QKlpxoVR+xtw==";
  };
  "@types/micromatch@4.0.10" = fetchurl {
    url = "https://registry.npmjs.org/@types/micromatch/-/micromatch-4.0.10.tgz";
    hash = "sha512-5jOhFDElqr4DKTrTEbnW8DZ4Hz5LRUEmyrGpCMrD/NphYv3nUnaF08xmSLx1rGGnyEs/kFnhiw6dCgcDqMr5PQ==";
  };
  "@types/node@25.3.2" = fetchurl {
    url = "https://registry.npmjs.org/@types/node/-/node-25.3.2.tgz";
    hash = "sha512-RpV6r/ij22zRRdyBPcxDeKAzH43phWVKEjL2iksqo1Vz3CuBUrgmPpPhALKiRfU7OMCmeeO9vECBMsV0hMTG8Q==";
  };
  "balanced-match@4.0.4" = fetchurl {
    url = "https://registry.npmjs.org/balanced-match/-/balanced-match-4.0.4.tgz";
    hash = "sha512-BLrgEcRTwX2o6gGxGOCNyMvGSp35YofuYzw9h1IMTRmKqttAZZVU67bdb9Pr2vUHA8+j3i2tJfjO6C6+4myGTA==";
  };
  "basic-ftp@5.2.0" = fetchurl {
    url = "https://registry.npmjs.org/basic-ftp/-/basic-ftp-5.2.0.tgz";
    hash = "sha512-VoMINM2rqJwJgfdHq6RiUudKt2BV+FY5ZFezP/ypmwayk68+NzzAQy4XXLlqsGD4MCzq3DrmNFD/uUmBJuGoXw==";
  };
  "brace-expansion@5.0.4" = fetchurl {
    url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-5.0.4.tgz";
    hash = "sha512-h+DEnpVvxmfVefa4jFbCf5HdH5YMDXRsmKflpf1pILZWRFlTbJpxeU55nJl4Smt5HQaGzg1o6RHFPJaOqnmBDg==";
  };
  "braces@3.0.3" = fetchurl {
    url = "https://registry.npmjs.org/braces/-/braces-3.0.3.tgz";
    hash = "sha512-yQbXgO/OSZVD2IsiLlro+7Hf6Q18EJrKSEsdoMzKePKXct3gvD8oLcOQdIzGupr5Fj+EDe8gO/lxc1BzfMpxvA==";
  };
  "bun-types@1.3.9" = fetchurl {
    url = "https://registry.npmjs.org/bun-types/-/bun-types-1.3.9.tgz";
    hash = "sha512-+UBWWOakIP4Tswh0Bt0QD0alpTY8cb5hvgiYeWCMet9YukHbzuruIEeXC2D7nMJPB12kbh8C7XJykSexEqGKJg==";
  };
  "bun2nix@2.0.8" = fetchurl {
    url = "https://registry.npmjs.org/bun2nix/-/bun2nix-2.0.8.tgz";
    hash = "sha512-pwq35hA81X1Kjsi5Xo69Aii9aY3zZHhWXwqF1QRz/uB35KzKbwJZ16WrhadiG9/T6bjOsRrPZtzuAyqmlXopLw==";
  };
  "clipboard-image@0.1.0" = fetchurl {
    url = "https://registry.npmjs.org/clipboard-image/-/clipboard-image-0.1.0.tgz";
    hash = "sha512-SWk7FgaXLNFld19peQ/rTe0n97lwR1WbkqxV6JKCAOh7U52AKV/PeMFCyt/8IhBdqyDA8rdyewQMKZqvWT5Akg==";
  };
  "clipboardy@5.3.1" = fetchurl {
    url = "https://registry.npmjs.org/clipboardy/-/clipboardy-5.3.1.tgz";
    hash = "sha512-fPWgBqpp9ctiOQCkE5yjYGzv11ZU55g6ahEgr3COiio6dXdt1mbchCPXQrSR2Y9sZqfi8L7QD3+UosgXVIuPdg==";
  };
  "cross-spawn@7.0.6" = fetchurl {
    url = "https://registry.npmjs.org/cross-spawn/-/cross-spawn-7.0.6.tgz";
    hash = "sha512-uV2QOWP2nWzsy2aMp8aRibhi9dlzF5Hgh5SHaB9OiTGEyDTiJJyx0uy51QXdyWbtAHNua4XJzUKca3OzKUd3vA==";
  };
  "crypto-random-string@4.0.0" = fetchurl {
    url = "https://registry.npmjs.org/crypto-random-string/-/crypto-random-string-4.0.0.tgz";
    hash = "sha512-x8dy3RnvYdlUcPOjkEHqozhiwzKNSq7GcPuXFbnyMOCHxX8V3OgIg/pYuabl2sbUPfIJaeAQB7PMOK8DFIdoRA==";
  };
  "dayjs@1.11.19" = fetchurl {
    url = "https://registry.npmjs.org/dayjs/-/dayjs-1.11.19.tgz";
    hash = "sha512-t5EcLVS6QPBNqM2z8fakk/NKel+Xzshgt8FFKAn+qwlD1pzZWxh0nVCrvFK7ZDb6XucZeF9z8C7CBWTRIVApAw==";
  };
  "escape-string-regexp@5.0.0" = fetchurl {
    url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-5.0.0.tgz";
    hash = "sha512-/veY75JbMK4j1yjvuUxuVsiS/hr/4iHs9FTT6cgTexxdE0Ly/glccBAkloH/DofkjRbZU3bnoj38mOmhkZ0lHw==";
  };
  "execa@5.1.1" = fetchurl {
    url = "https://registry.npmjs.org/execa/-/execa-5.1.1.tgz";
    hash = "sha512-8uSpZZocAZRBAPIEINJj3Lo9HyGitllczc27Eh5YYojjMFMn8yHMDMaUHE2Jqfq05D/wucwI4JGURyXt1vchyg==";
  };
  "execa@9.6.1" = fetchurl {
    url = "https://registry.npmjs.org/execa/-/execa-9.6.1.tgz";
    hash = "sha512-9Be3ZoN4LmYR90tUoVu2te2BsbzHfhJyfEiAVfz7N5/zv+jduIfLrV2xdQXOHbaD6KgpGdO9PRPM1Y4Q9QkPkA==";
  };
  "figures@6.1.0" = fetchurl {
    url = "https://registry.npmjs.org/figures/-/figures-6.1.0.tgz";
    hash = "sha512-d+l3qxjSesT4V7v2fh+QnmFnUWv9lSpjarhShNTgBOfA0ttejbQUAlHLitbjkoRiDulW0OPoQPYIGhIC8ohejg==";
  };
  "fill-range@7.1.1" = fetchurl {
    url = "https://registry.npmjs.org/fill-range/-/fill-range-7.1.1.tgz";
    hash = "sha512-YsGpe3WHLK8ZYi4tWDg2Jy3ebRz2rXowDxnld4bkQB00cc/1Zw9AWnC0i9ztDJitivtQvaI9KaLyKrc+hBW0yg==";
  };
  "get-stream@6.0.1" = fetchurl {
    url = "https://registry.npmjs.org/get-stream/-/get-stream-6.0.1.tgz";
    hash = "sha512-ts6Wi+2j3jQjqi70w5AlN8DFnkSwC+MqmxEzdEALB2qXZYV3X/b1CTfgPLGJNMeAWxdPfU8FO1ms3NUfaHCPYg==";
  };
  "get-stream@9.0.1" = fetchurl {
    url = "https://registry.npmjs.org/get-stream/-/get-stream-9.0.1.tgz";
    hash = "sha512-kVCxPF3vQM/N0B1PmoqVUqgHP+EeVjmZSQn+1oCRPxd2P21P2F19lIgbR3HBosbB1PUhOAoctJnfEn2GbN2eZA==";
  };
  "glob@13.0.6" = fetchurl {
    url = "https://registry.npmjs.org/glob/-/glob-13.0.6.tgz";
    hash = "sha512-Wjlyrolmm8uDpm/ogGyXZXb1Z+Ca2B8NbJwqBVg0axK9GbBeoS7yGV6vjXnYdGm6X53iehEuxxbyiKp8QmN4Vw==";
  };
  "hotscript@1.0.13" = fetchurl {
    url = "https://registry.npmjs.org/hotscript/-/hotscript-1.0.13.tgz";
    hash = "sha512-C++tTF1GqkGYecL+2S1wJTfoH6APGAsbb7PAWQ3iVIwgG/EFseAfEVOKFgAFq4yK3+6j1EjUD4UQ9dRJHX/sSQ==";
  };
  "human-signals@2.1.0" = fetchurl {
    url = "https://registry.npmjs.org/human-signals/-/human-signals-2.1.0.tgz";
    hash = "sha512-B4FFZ6q/T2jhhksgkbEW3HBvWIfDW85snkQgawt07S7J5QXTk6BkNV+0yAeZrM5QpMAdYlocGoljn0sJ/WQkFw==";
  };
  "human-signals@8.0.1" = fetchurl {
    url = "https://registry.npmjs.org/human-signals/-/human-signals-8.0.1.tgz";
    hash = "sha512-eKCa6bwnJhvxj14kZk5NCPc6Hb6BdsU9DZcOnmQKSnO1VKrfV0zCvtttPZUsBvjmNDn8rpcJfpwSYnHBjc95MQ==";
  };
  "is-docker@3.0.0" = fetchurl {
    url = "https://registry.npmjs.org/is-docker/-/is-docker-3.0.0.tgz";
    hash = "sha512-eljcgEDlEns/7AXFosB5K/2nCM4P7FQPkGc/DWLy5rmFEWvZayGrik1d9/QIY5nJ4f9YsVvBkA6kJpHn9rISdQ==";
  };
  "is-inside-container@1.0.0" = fetchurl {
    url = "https://registry.npmjs.org/is-inside-container/-/is-inside-container-1.0.0.tgz";
    hash = "sha512-KIYLCCJghfHZxqjYBE7rEy0OBuTd5xCHS7tHVgvCLkx7StIoaxwNW3hCALgEUjFfeRk+MG/Qxmp/vtETEF3tRA==";
  };
  "is-number@7.0.0" = fetchurl {
    url = "https://registry.npmjs.org/is-number/-/is-number-7.0.0.tgz";
    hash = "sha512-41Cifkg6e8TylSpdtTpeLVMqvSBEVzTttHvERD741+pnZ8ANv0004MRL43QKPDlK9cGvNp6NZWZUBlbGXYxxng==";
  };
  "is-plain-obj@4.1.0" = fetchurl {
    url = "https://registry.npmjs.org/is-plain-obj/-/is-plain-obj-4.1.0.tgz";
    hash = "sha512-+Pgi+vMuUNkJyExiMBt5IlFoMyKnr5zhJ4Uspz58WOhBF5QoIZkFyNHIbBAtHwzVAgk5RtndVNsDRN61/mmDqg==";
  };
  "is-stream@2.0.1" = fetchurl {
    url = "https://registry.npmjs.org/is-stream/-/is-stream-2.0.1.tgz";
    hash = "sha512-hFoiJiTl63nn+kstHGBtewWSKnQLpyb155KHheA1l39uvtO9nWIop1p3udqPcUd/xbF1VLMO4n7OI6p7RbngDg==";
  };
  "is-stream@4.0.1" = fetchurl {
    url = "https://registry.npmjs.org/is-stream/-/is-stream-4.0.1.tgz";
    hash = "sha512-Dnz92NInDqYckGEUJv689RbRiTSEHCQ7wOVeALbkOz999YpqT46yMRIGtSNl2iCL1waAZSx40+h59NV/EwzV/A==";
  };
  "is-unicode-supported@2.1.0" = fetchurl {
    url = "https://registry.npmjs.org/is-unicode-supported/-/is-unicode-supported-2.1.0.tgz";
    hash = "sha512-mE00Gnza5EEB3Ds0HfMyllZzbBrmLOX3vfWoj9A9PEnTfratQ/BcaJOuMhnkhjXvb2+FkY3VuHqtAGpTPmglFQ==";
  };
  "is-wayland@0.1.0" = fetchurl {
    url = "https://registry.npmjs.org/is-wayland/-/is-wayland-0.1.0.tgz";
    hash = "sha512-QkbMsWkIfkrzOPxenwye0h56iAXirZYHG9eHVPb22fO9y+wPbaX/CHacOWBa/I++4ohTcByimhM1/nyCsH8KNA==";
  };
  "is-wsl@3.1.1" = fetchurl {
    url = "https://registry.npmjs.org/is-wsl/-/is-wsl-3.1.1.tgz";
    hash = "sha512-e6rvdUCiQCAuumZslxRJWR/Doq4VpPR82kqclvcS0efgt430SlGIk05vdCN58+VrzgtIcfNODjozVielycD4Sw==";
  };
  "is64bit@2.0.0" = fetchurl {
    url = "https://registry.npmjs.org/is64bit/-/is64bit-2.0.0.tgz";
    hash = "sha512-jv+8jaWCl0g2lSBkNSVXdzfBA0npK1HGC2KtWM9FumFRoGS94g3NbCCLVnCYHLjp4GrW2KZeeSTMo5ddtznmGw==";
  };
  "isexe@2.0.0" = fetchurl {
    url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
    hash = "sha512-RHxMLp9lnKHGHRng9QFhRCMbYAcVpn69smSGcq3f36xjgVVWThj4qqLbTLlq7Ssj8B+fIQ1EuCEGI2lKsyQeIw==";
  };
  "iteragain@4.1.6" = fetchurl {
    url = "https://registry.npmjs.org/iteragain/-/iteragain-4.1.6.tgz";
    hash = "sha512-3cw08yvlVI7LNbW9Dy9mnRrIKIYzXIbqxVO0PZ1++lIAKk1sgGIL2tUZ9leRH+AZzJOz7rSs/RQgtGNYTPcveg==";
  };
  "lru-cache@11.2.6" = fetchurl {
    url = "https://registry.npmjs.org/lru-cache/-/lru-cache-11.2.6.tgz";
    hash = "sha512-ESL2CrkS/2wTPfuend7Zhkzo2u0daGJ/A2VucJOgQ/C48S/zB8MMeMHSGKYpXhIjbPxfuezITkaBH1wqv00DDQ==";
  };
  "macos-version@6.0.0" = fetchurl {
    url = "https://registry.npmjs.org/macos-version/-/macos-version-6.0.0.tgz";
    hash = "sha512-O2S8voA+pMfCHhBn/TIYDXzJ1qNHpPDU32oFxglKnVdJABiYYITt45oLkV9yhwA3E2FDwn3tQqUFrTsr1p3sBQ==";
  };
  "meow@14.1.0" = fetchurl {
    url = "https://registry.npmjs.org/meow/-/meow-14.1.0.tgz";
    hash = "sha512-EDYo6VlmtnumlcBCbh1gLJ//9jvM/ndXHfVXIFrZVr6fGcwTUyCTFNTLCKuY3ffbK8L/+3Mzqnd58RojiZqHVw==";
  };
  "merge-stream@2.0.0" = fetchurl {
    url = "https://registry.npmjs.org/merge-stream/-/merge-stream-2.0.0.tgz";
    hash = "sha512-abv/qOcuPfk3URPfDzmZU1LKmuw8kT+0nIHvKrKgFrwifol/doWcdA4ZqsWQ8ENrFKkd67Mfpo/LovbIUsbt3w==";
  };
  "micromatch@4.0.8" = fetchurl {
    url = "https://registry.npmjs.org/micromatch/-/micromatch-4.0.8.tgz";
    hash = "sha512-PXwfBhYu0hBCPw8Dn0E+WDYb7af3dSLVWKi3HGv84IdF4TyFoC0ysxFd0Goxw7nSv4T/PzEJQxsYsEiFCKo2BA==";
  };
  "mimic-fn@2.1.0" = fetchurl {
    url = "https://registry.npmjs.org/mimic-fn/-/mimic-fn-2.1.0.tgz";
    hash = "sha512-OqbOk5oEQeAZ8WXWydlu9HJjz9WVdEIvamMCcXmuqUYjTknH/sqsWvhQ3vgwKFRR1HpjvNBKQ37nbJgYzGqGcg==";
  };
  "minimatch@10.2.4" = fetchurl {
    url = "https://registry.npmjs.org/minimatch/-/minimatch-10.2.4.tgz";
    hash = "sha512-oRjTw/97aTBN0RHbYCdtF1MQfvusSIBQM0IZEgzl6426+8jSC0nF1a/GmnVLpfB9yyr6g6FTqWqiZVbxrtaCIg==";
  };
  "minipass@7.1.3" = fetchurl {
    url = "https://registry.npmjs.org/minipass/-/minipass-7.1.3.tgz";
    hash = "sha512-tEBHqDnIoM/1rXME1zgka9g6Q2lcoCkxHLuc7ODJ5BxbP5d4c2Z5cGgtXAku59200Cx7diuHTOYfSBD8n6mm8A==";
  };
  "moderndash@4.0.0" = fetchurl {
    url = "https://registry.npmjs.org/moderndash/-/moderndash-4.0.0.tgz";
    hash = "sha512-77kEJCsBo3YzqIrO4ZWHo1h7q8f8ZIRxQ0DE0fEvj3rZWsfTMLeRzctBjkz2zKM1BAIQsOqB79jm3dZ4RDFmqw==";
  };
  "mri@1.2.0" = fetchurl {
    url = "https://registry.npmjs.org/mri/-/mri-1.2.0.tgz";
    hash = "sha512-tzzskb3bG8LvYGFF/mDTpq3jpI6Q9wc3LEmBaghu+DdCssd1FakN7Bc0hVNmEyGq1bq3RgfkCb3cmQLpNPOroA==";
  };
  "npm-run-path@4.0.1" = fetchurl {
    url = "https://registry.npmjs.org/npm-run-path/-/npm-run-path-4.0.1.tgz";
    hash = "sha512-S48WzZW777zhNIrn7gxOlISNAqi9ZC/uQFnRdbeIHhZhCA6UqpkOT8T1G7BvfdgP4Er8gF4sUbaS0i7QvIfCWw==";
  };
  "npm-run-path@6.0.0" = fetchurl {
    url = "https://registry.npmjs.org/npm-run-path/-/npm-run-path-6.0.0.tgz";
    hash = "sha512-9qny7Z9DsQU8Ou39ERsPU4OZQlSTP47ShQzuKZ6PRXpYLtIFgl/DEBYEXKlvcEa+9tHVcK8CF81Y2V72qaZhWA==";
  };
  "onetime@5.1.2" = fetchurl {
    url = "https://registry.npmjs.org/onetime/-/onetime-5.1.2.tgz";
    hash = "sha512-kbpaSSGJTWdAY5KPVeMOKXSrPtr8C8C7wodJbcsd51jRnmD+GZu8Y0VoU6Dm5Z4vWr0Ig/1NKuWRKf7j5aaYSg==";
  };
  "parse-ms@4.0.0" = fetchurl {
    url = "https://registry.npmjs.org/parse-ms/-/parse-ms-4.0.0.tgz";
    hash = "sha512-TXfryirbmq34y8QBwgqCVLi+8oA3oWx2eAnSn62ITyEhEYaWRlVZ2DvMM9eZbMs/RfxPu/PK/aBLyGj4IrqMHw==";
  };
  "path-key@3.1.1" = fetchurl {
    url = "https://registry.npmjs.org/path-key/-/path-key-3.1.1.tgz";
    hash = "sha512-ojmeN0qd+y0jszEtoY48r0Peq5dwMEkIlCOu6Q5f41lfkswXuKtYrhgoTpLnyIcHm24Uhqx+5Tqm2InSwLhE6Q==";
  };
  "path-key@4.0.0" = fetchurl {
    url = "https://registry.npmjs.org/path-key/-/path-key-4.0.0.tgz";
    hash = "sha512-haREypq7xkM7ErfgIyA0z+Bj4AGKlMSdlQE2jvJo6huWD1EdkKYV+G/T4nq0YEF2vgTT8kqMFKo1uHn950r4SQ==";
  };
  "path-scurry@2.0.2" = fetchurl {
    url = "https://registry.npmjs.org/path-scurry/-/path-scurry-2.0.2.tgz";
    hash = "sha512-3O/iVVsJAPsOnpwWIeD+d6z/7PmqApyQePUtCndjatj/9I5LylHvt5qluFaBT3I5h3r1ejfR056c+FCv+NnNXg==";
  };
  "picomatch@2.3.1" = fetchurl {
    url = "https://registry.npmjs.org/picomatch/-/picomatch-2.3.1.tgz";
    hash = "sha512-JU3teHTNjmE2VCGFzuY8EXzCDVwEqB2a8fsIvwaStHhAWJEeVd1o1QD80CU6+ZdEXXSLbSsuLwJjkCBWqRQUVA==";
  };
  "powershell-utils@0.2.0" = fetchurl {
    url = "https://registry.npmjs.org/powershell-utils/-/powershell-utils-0.2.0.tgz";
    hash = "sha512-ZlsFlG7MtSFCoc5xreOvBAozCJ6Pf06opgJjh9ONEv418xpZSAzNjstD36C6+JwOnfSqOW/9uDkqKjezTdxZhw==";
  };
  "pretty-ms@9.3.0" = fetchurl {
    url = "https://registry.npmjs.org/pretty-ms/-/pretty-ms-9.3.0.tgz";
    hash = "sha512-gjVS5hOP+M3wMm5nmNOucbIrqudzs9v/57bWRHQWLYklXqoXKrVfYW2W9+glfGsqtPgpiz5WwyEEB+ksXIx3gQ==";
  };
  "run-jxa@3.0.0" = fetchurl {
    url = "https://registry.npmjs.org/run-jxa/-/run-jxa-3.0.0.tgz";
    hash = "sha512-4f2CrY7H+sXkKXJn/cE6qRA3z+NMVO7zvlZ/nUV0e62yWftpiLAfw5eV9ZdomzWd2TXWwEIiGjAT57+lWIzzvA==";
  };
  "sade@1.8.1" = fetchurl {
    url = "https://registry.npmjs.org/sade/-/sade-1.8.1.tgz";
    hash = "sha512-xal3CZX1Xlo/k4ApwCFrHVACi9fBqJ7V+mwhBsuf/1IOKbBy098Fex+Wa/5QMubw09pSZ/u8EY8PWgevJsXp1A==";
  };
  "semver@7.7.4" = fetchurl {
    url = "https://registry.npmjs.org/semver/-/semver-7.7.4.tgz";
    hash = "sha512-vFKC2IEtQnVhpT78h1Yp8wzwrf8CM+MzKMHGJZfBtzhZNycRFnXsHk6E5TxIkkMsgNS7mdX3AGB7x2QM2di4lA==";
  };
  "shebang-command@2.0.0" = fetchurl {
    url = "https://registry.npmjs.org/shebang-command/-/shebang-command-2.0.0.tgz";
    hash = "sha512-kHxr2zZpYtdmrN1qDjrrX/Z1rR1kG8Dx+gkpK1G4eXmvXswmcE1hTWBWYUzlraYw1/yZp6YuDY77YtvbN0dmDA==";
  };
  "shebang-regex@3.0.0" = fetchurl {
    url = "https://registry.npmjs.org/shebang-regex/-/shebang-regex-3.0.0.tgz";
    hash = "sha512-7++dFhtcx3353uBaq8DDR4NuxBetBzC7ZQOhmTQInHEd6bSrXdiEyzCvG07Z44UYdLShWUyXt5M/yhz8ekcb1A==";
  };
  "signal-exit@3.0.7" = fetchurl {
    url = "https://registry.npmjs.org/signal-exit/-/signal-exit-3.0.7.tgz";
    hash = "sha512-wnD2ZE+l+SPC/uoS0vXeE9L1+0wuaMqKlfz9AMUo38JsyLSBWSFcHR1Rri62LZc12vLr1gb3jl7iwQhgwpAbGQ==";
  };
  "signal-exit@4.1.0" = fetchurl {
    url = "https://registry.npmjs.org/signal-exit/-/signal-exit-4.1.0.tgz";
    hash = "sha512-bzyZ1e88w9O1iNJbKnOlvYTrWPDl46O1bG0D3XInv+9tkPrxrN8jUUTiFlDkkmKWgn1M6CfIA13SuGqOa9Korw==";
  };
  "strip-final-newline@2.0.0" = fetchurl {
    url = "https://registry.npmjs.org/strip-final-newline/-/strip-final-newline-2.0.0.tgz";
    hash = "sha512-BrpvfNAE3dcvq7ll3xVumzjKjZQ5tI1sEUIKr3Uoks0XUl45St3FlatVqef9prk4jRDzhW6WZg+3bk93y6pLjA==";
  };
  "strip-final-newline@4.0.0" = fetchurl {
    url = "https://registry.npmjs.org/strip-final-newline/-/strip-final-newline-4.0.0.tgz";
    hash = "sha512-aulFJcD6YK8V1G7iRB5tigAP4TsHBZZrOV8pjV++zdUwmeV8uzbY7yn6h9MswN62adStNZFuCIx4haBnRuMDaw==";
  };
  "subsume@4.0.0" = fetchurl {
    url = "https://registry.npmjs.org/subsume/-/subsume-4.0.0.tgz";
    hash = "sha512-BWnYJElmHbYZ/zKevy+TG+SsyoFCmRPDHJbR1MzLxkPOv1Jp/4hGhVUtP98s+wZBsBsHwCXvPTP0x287/WMjGg==";
  };
  "system-architecture@0.1.0" = fetchurl {
    url = "https://registry.npmjs.org/system-architecture/-/system-architecture-0.1.0.tgz";
    hash = "sha512-ulAk51I9UVUyJgxlv9M6lFot2WP3e7t8Kz9+IS6D4rVba1tR9kON+Ey69f+1R4Q8cd45Lod6a4IcJIxnzGc/zA==";
  };
  "to-regex-range@5.0.1" = fetchurl {
    url = "https://registry.npmjs.org/to-regex-range/-/to-regex-range-5.0.1.tgz";
    hash = "sha512-65P7iz6X5yEr1cwcgvQxbbIw7Uk3gOy5dIdtZ4rDveLqhrdJP+Li/Hx6tyK0NEb+2GCyneCMJiGqrADCSNk8sQ==";
  };
  "type-fest@1.4.0" = fetchurl {
    url = "https://registry.npmjs.org/type-fest/-/type-fest-1.4.0.tgz";
    hash = "sha512-yGSza74xk0UG8k+pLh5oeoYirvIiWo5t0/o3zHHAO2tRDiZcxWP7fywNlXhqb6/r6sWvwi+RsyQMWhVLe4BVuA==";
  };
  "type-fest@2.19.0" = fetchurl {
    url = "https://registry.npmjs.org/type-fest/-/type-fest-2.19.0.tgz";
    hash = "sha512-RAH822pAdBgcNMAfWnCBU3CFZcfZ/i1eZjwFU/dsLKumyuuP3niueg2UAukXYF0E2AAoc82ZSSf9J0WQBinzHA==";
  };
  "type-fest@4.27.0" = fetchurl {
    url = "https://registry.npmjs.org/type-fest/-/type-fest-4.27.0.tgz";
    hash = "sha512-3IMSWgP7C5KSQqmo1wjhKrwsvXAtF33jO3QY+Uy++ia7hqvgSK6iXbbg5PbDBc1P2ZbNEDgejOrN4YooXvhwCw==";
  };
  "typescript@5.9.3" = fetchurl {
    url = "https://registry.npmjs.org/typescript/-/typescript-5.9.3.tgz";
    hash = "sha512-jl1vZzPDinLr9eUt3J/t7V6FgNEw9QjvBPdysz9KfQDD41fQrC2Y4vKQdiaUpFT4bXlb1RHhLpp8wtm6M5TgSw==";
  };
  "undici-types@7.18.2" = fetchurl {
    url = "https://registry.npmjs.org/undici-types/-/undici-types-7.18.2.tgz";
    hash = "sha512-AsuCzffGHJybSaRrmr5eHr81mwJU3kjw6M+uprWvCXiNeN9SOGwQ3Jn8jb8m3Z6izVgknn1R0FTCEAP2QrLY/w==";
  };
  "unicorn-magic@0.3.0" = fetchurl {
    url = "https://registry.npmjs.org/unicorn-magic/-/unicorn-magic-0.3.0.tgz";
    hash = "sha512-+QBBXBCvifc56fsbuxZQ6Sic3wqqc3WWaqxs58gvJrcOuN83HGTCwz3oS5phzU9LthRNE9VrJCFCLUgHeeFnfA==";
  };
  "unique-string@3.0.0" = fetchurl {
    url = "https://registry.npmjs.org/unique-string/-/unique-string-3.0.0.tgz";
    hash = "sha512-VGXBUVwxKMBUznyffQweQABPRRW1vHZAbadFZud4pLFAqRGvv/96vafgjWFqzourzr8YonlQiPgH0YCJfawoGQ==";
  };
  "which@2.0.2" = fetchurl {
    url = "https://registry.npmjs.org/which/-/which-2.0.2.tgz";
    hash = "sha512-BLI3Tl1TW3Pvl70l3yq3Y64i+awpwXqsGBYWkkqMtnbXgrMD+yj7rhW0kuEDxzJaYXGjEW5ogapKNMEKNMjibA==";
  };
  "yoctocolors@2.1.2" = fetchurl {
    url = "https://registry.npmjs.org/yoctocolors/-/yoctocolors-2.1.2.tgz";
    hash = "sha512-CzhO+pFNo8ajLM2d2IW/R93ipy99LWjtwblvC1RsoSUMZgyLbYFr221TnSNT7GjGdYui6P459mw9JH/g/zW2ug==";
  };
}
