keys:
  # Created by `age` using:
  # nix shell nixpkgs#age -c age-keygen -y ~/.config/sops/age/keys.txt
  - &primary age1ct7kyrr2p9r4rveqrfvx5lw696j9rc0stz8dm64uyclamc0vj46qdqqrrl
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
    - age:
      - *primary
