update:
	sudo nix flake update --flake .

build:
	sudo darwin-rebuild build --flake .

switch:
	sudo darwin-rebuild switch --flake .

list-generations:
	sudo darwin-rebuild --list-generations --flake .
