export const STYLE_CLASSES = [
  "selected",
  "btn-ghost",
  "circular",
  "rounded-none",
  "rounded-sm",
  "rounded-md",
  "rounded-lg",
  "rounded-xl",
  "rounded-full",
  "rounded-l",
  "rounded-r",
  "rounded-t",
  "rounded-b",
  "border",
  "m-xs",
  "m-sm",
  "m-md",
  "m-lg",
  "m-xl",
  "mx-xs",
  "mx-sm",
  "my-xs",
  "my-sm",
  "p-xs",
  "p-sm",
  "p-md",
  "p-lg",
  "p-xl",
  "px-sm",
  "py-sm",
  "bg-transparent",
  "bg-bg-color",
  "bg-fg-color",
  "bg-selected",
  "color-fg-color",
  "color-bg-color",
  "color-selected",
  "opacity-90",
  "font-size-xs",
  "font-size-sm",
  "font-size-md",
  "font-size-lg"
] as const;

export type StyleClass = (typeof STYLE_CLASSES)[number];